import { CmsNavigation } from "@/components/CmsNavigation";
import './globals.css'
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col w-full">
          <CmsNavigation />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
